# Permalinks
permalink:            /:year-:month-:day/:title.html

safe:                 false
source:               .
destination:          _site
layouts_dir:          _layouts
data_dir:             _data
include:              [".htaccess"]
exclude:              [".git"]
keep_files:           []

show_drafts:          null
future:               true
unpublished:          false
markdown:             kramdown
markdown_ext:         "md"
excerpt_separator:    "<!--more-->"
highlighter:          rouge

syntax-highlighting:
  enabled :           true
  css:                css/syntax.css

kramdown:
  input:              GFM
  auto_ids:           true
  footnote_nr:        1
  entity_output:      as_char
  toc_levels:         1..6
  smart_quotes:       lsquo,rsquo,ldquo,rdquo
  enable_coderay:     true
  syntax_highlighter: rouge

whitelist:            []
gems:
  - jemoji
#  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
#  - jekyll-seo-tag

sass:
  sass_dir:           src/_sass
  style:              :compact

# Setup
title:                OanhNN
tagline:              'Sharing anything i know and i think'
description:          'Sharing anything I know and I think'
url:                  https://oanhnn.github.io
baseurl:              ''
timezone:             Asia/Ho_Chi_Minh
encoding:             utf-8
locale:               vi_VN
paginate:             5
paginate_path:        "/page:num/"

# Default vars
defaults:
  layout:            post
  type:              blog

# About/contact
author:
  name:              Oanh Nguyen
  url:               https://oanhnn.github.io/about
  email:             oanhnn.bk@gmail.com
  image:             https://en.gravatar.com/userimage/35625823/e3d572ec75073250dc4901b93fba3cef.jpg?size=200
  github:            https://github.com/oanhnn
  twitter:           https://twitter.com/oanhnn
  facebook:          https://facebook.com/oanhnn
  rss:               https://oanhnn.github.io/atom.xml
  skype:             skype:ngocoanh.bk52?chat

# Custom vars
google_analytics:    UA-46600142-1
disqus_shortname:    oanhnn
